name: first
author: markm
description: My first action

inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  run-timestamp:
    description: "Timestamp this was run"
    value: ${{ steps.run-timestamp-generator.outputs.run-timestamp }}

runs:
  using: "composite"
  steps:
    - name: Display env
      run: env
      shell: bash

    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Run Timestamp Generator
      id: run-timestamp-generator
      run: echo "run-timestamp=$(date "+%d/%m/%Y %H:%M:%S")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run goodbye.sh
      run: goodbye.sh "${{ inputs.who-to-greet }}"
      shell: bash
